### PR TITLE
add brazilian portuguese translation

### PR DESCRIPTION
**Pull request by victor-borges**
Adds brazilian portuguese translation (hope I did the generating steps right).
There was a section about inverting gyro axis and asking for pictures or text, I kept the information in english (like Manufacturer and Product) as those seem to be for the devs to make sense of, and not the user (mostly).

### CODE REVIEW

**Comment by antheas** [comment]
Thanks Victor. Translations are not supported yet. I added the export to get translations started and received the chinese translations a few days ago. So I will get that going hopefully next week.

I will merge your pull requests too then, and I will be in touch. It is good that you updated the translations before you did the work, as the chinese translation will need to be updated too now.

**Comment by antheas** [comment]
Hi Victor, I added initial localization to hhd. 

At your leisure, can you do the following?

Copying your translated Portuguese file to `./i18n/pt/LC_MESSAGES/hhd.po` of the current repository.

Running the following:
```bash
pybabel init -i i18n/adjustor.pot -d i18n -D adjustor -l pt
pybabel update -i i18n/hhd.pot -d i18n -D hhd -l pt
```

Updating the translations.

Then force push to this pull request `git push -f` so I can merge Portuguese.

Thanks and sorry for the wait. 

I prioritized some other features, which I hope you are enjoying.

If you don't want to translate further, I can also cherry pick your Portuguese file as is and someone else can move it further.

**Comment by antheas** [comment]
image

Preview of the Chinese translation I have on hand.

**Comment by victor-borges** [comment]
I force-pushed to sync my fork and github closed the PR 🫠

**Comment by victor-borges** [comment]
> I prioritized some other features, which I hope you are enjoying.
I'm VERY MUCH enjoying everything being made here, wanted to contribute back in the small ways that I can, and by advocating for Bazzite and HHD in every opportunity! Thank you so much!

**Comment by antheas** [comment]
Nice!

**Comment by antheas** [comment]
https://github.com/hhd-dev/hhd/releases/tag/v2.6.1

**Pull request merged**
